"""SQLAlchemy 2.0 async ORM domain models (SPEC.md §2).

Four tables:
  - `Encounter` — a read-through mirror of a FHIR `Encounter` resource.
    This is a cache, NOT the source of truth (that's the FHIR server); it
    exists so RBAC ownership checks and encounter listing don't require a
    live FHIR round-trip on every request.
  - `DraftNote`, `SummaryRequest`, `AuditEvent` — authoritative local state
    owned by this service.

All four subclass the shared `Base` from `banner_copilot.db` so Alembic's
`target_metadata = Base.metadata` (see migrations/env.py) picks them all up.

Dialect notes:
  - JSON-ish columns use `sqlalchemy.dialects.postgresql.JSONB` (this app
    only ever runs against Postgres 16, per docker-compose.yml).
  - UUID primary keys use `sqlalchemy.dialects.postgresql.UUID(as_uuid=True)`
    with a Python-side `default=uuid.uuid4` (not a DB-side default/
    `gen_random_uuid()`) — the id is generated by the ORM before insert.
  - `DraftNote.status`, `SummaryRequest.review_status`, and
    `AuditEvent.outcome` use Python `str` Enums wrapped in a SQLAlchemy
    `Enum(..., native_enum=False, create_constraint=True)`. That renders as
    a plain VARCHAR column with a CHECK constraint at the DB level (not a
    Postgres native ENUM type) while still giving Python-side type safety
    and self-documenting allowed values.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import DateTime, Integer, String
from sqlalchemy import Enum as SQLAlchemyEnum
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from banner_copilot.db import Base


class DraftNoteStatus(str, enum.Enum):
    """Allowed `DraftNote.status` values (SPEC.md §2, §6 Grok gating)."""

    DRAFTED = "drafted"
    DRAFTED_FLAGGED = "drafted_flagged"
    DRAFTED_UNVERIFIED = "drafted_unverified"
    EDITED = "edited"
    SIGNED = "signed"
    FAILED = "failed"


class SummaryReviewStatus(str, enum.Enum):
    """Allowed `SummaryRequest.review_status` values (SPEC.md §2, §6)."""

    CLEAN = "clean"
    FLAGGED = "flagged"
    UNVERIFIED = "unverified"


class AuditOutcome(str, enum.Enum):
    """Allowed `AuditEvent.outcome` values (SPEC.md §2)."""

    SUCCESS = "success"
    FAILURE = "failure"


def _enum_values(enum_cls: type[enum.Enum]) -> list[str]:
    """`values_callable` for SQLAlchemy Enum columns: use `.value`, not `.name`."""
    return [member.value for member in enum_cls]


class Encounter(Base):
    """Local mirror of a FHIR `Encounter` resource (cache, not source of truth).

    `id` IS the FHIR Encounter id (e.g. "encounter-1") — not a separately
    generated surrogate key — so it can be joined against directly.
    """

    __tablename__ = "encounters"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    patient_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    attending_practitioner_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    status: Mapped[str] = mapped_column(String, nullable=False)
    period_start: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    period_end: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    synced_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class DraftNote(Base):
    """A Claude-drafted, Grok-reviewed SOAP note for one encounter (SPEC.md §2, §6)."""

    __tablename__ = "draft_notes"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    # Logically FK -> encounters.id, but deliberately NOT a hard FK constraint:
    # the Encounter mirror row may not exist locally yet the first time this
    # encounter is touched (SPEC.md §7's two-phase fetch populates the mirror
    # lazily), and this table must not fail to insert because of that.
    encounter_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    status: Mapped[DraftNoteStatus] = mapped_column(
        SQLAlchemyEnum(
            DraftNoteStatus,
            name="draft_note_status",
            native_enum=False,
            create_constraint=True,
            values_callable=_enum_values,
        ),
        nullable=False,
    )
    draft_text: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    edited_text: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    diff: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    prompt_template_version: Mapped[str | None] = mapped_column(String, nullable=True)
    claude_model: Mapped[str | None] = mapped_column(String, nullable=True)
    grok_review: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    failure_reason: Mapped[str | None] = mapped_column(String, nullable=True)
    created_by: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
    signed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class SummaryRequest(Base):
    """A Claude-generated, Grok-reviewed patient longitudinal summary (SPEC.md §2, §6)."""

    __tablename__ = "summary_requests"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    patient_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    summary_text: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    review_status: Mapped[SummaryReviewStatus] = mapped_column(
        SQLAlchemyEnum(
            SummaryReviewStatus,
            name="summary_review_status",
            native_enum=False,
            create_constraint=True,
            values_callable=_enum_values,
        ),
        nullable=False,
    )
    prompt_template_version: Mapped[str | None] = mapped_column(String, nullable=True)
    claude_model: Mapped[str | None] = mapped_column(String, nullable=True)
    grok_review: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    # Python-side default (cache TTL, not a DB-enforced constraint).
    ttl_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=900)


class AuditEvent(Base):
    """Immutable audit trail row (SPEC.md §2, §10) — one per FHIR read / LLM call / note action."""

    __tablename__ = "audit_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    actor: Mapped[str] = mapped_column(String, nullable=False)
    action: Mapped[str] = mapped_column(String, nullable=False)
    resource_type: Mapped[str] = mapped_column(String, nullable=False)
    resource_id: Mapped[str] = mapped_column(String, nullable=False)
    outcome: Mapped[AuditOutcome] = mapped_column(
        SQLAlchemyEnum(
            AuditOutcome,
            name="audit_outcome",
            native_enum=False,
            create_constraint=True,
            values_callable=_enum_values,
        ),
        nullable=False,
    )
    detail: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
