"""Grok-only: independent grounding review of a Claude draft/summary (SPEC.md
§6, FR-6 — the "multi-agent review system").

Provider isolation: this file calls the OpenAI-compatible SDK against xAI's
endpoint exclusively. Claude/Anthropic calls live in `llm/claude_drafting.py`
and are never mixed into this module.

Runs only *after* Claude has already produced a draft/summary. Receives the
exact same structured FHIR facts Claude received, plus Claude's output — never
anything Claude wasn't also given (no PHI-boundary widening). The task is
strictly bounded to grounding/consistency, not a second clinical opinion: for
every clinical claim, verify it traces to a supplied fact; flag claims that
don't, internal contradictions, and material omissions of supplied facts.

The caller (`domain/service.py`) owns the actual status-gating transitions
(`drafted` / `drafted_flagged` / `drafted_unverified`) — this module only
returns a validated `GrokReviewResult` or raises `GrokUnavailableError`.
"""

from __future__ import annotations

import json
from typing import Literal

import openai
from pydantic import BaseModel, ValidationError

from banner_copilot.config import get_settings

_SYSTEM_PROMPT = (
    "You are an independent grounding reviewer for clinical documentation "
    "generated by another AI model. You will be given the structured clinical "
    "facts (JSON) that were supplied to that model, and the content it "
    "generated from them. Your only job is grounding and consistency — NOT a "
    "second clinical opinion, NOT a judgment on clinical appropriateness. For "
    "every clinical claim in the generated content: verify it traces to a fact "
    "present in the supplied JSON. Flag as a 'critical' finding any claim that "
    "is not supported by the supplied facts, or any internal contradiction "
    "within the generated content. Flag as a 'warning' finding any material "
    "supplied fact the generated content omitted. Do not flag stylistic or "
    "phrasing choices."
)

_REVIEW_SCHEMA = {
    "type": "object",
    "properties": {
        "grounded": {"type": "boolean"},
        "findings": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "severity": {"type": "string", "enum": ["critical", "warning"]},
                    "claim": {"type": "string"},
                    "issue": {"type": "string"},
                },
                "required": ["severity", "claim", "issue"],
                "additionalProperties": False,
            },
        },
        "overall_assessment": {"type": "string"},
    },
    "required": ["grounded", "findings", "overall_assessment"],
    "additionalProperties": False,
}


class GrokFinding(BaseModel):
    severity: Literal["critical", "warning"]
    claim: str
    issue: str


class GrokReviewResult(BaseModel):
    grounded: bool
    findings: list[GrokFinding]
    overall_assessment: str


class GrokUnavailableError(Exception):
    """Grok call failed, timed out, or returned invalid/non-conforming JSON.
    Treated identically regardless of cause — maps to `status = "drafted_unverified"`."""


def has_critical_finding(review: GrokReviewResult) -> bool:
    return any(finding.severity == "critical" for finding in review.findings)


async def _review(*, facts: dict, generated_content: dict, content_label: str) -> GrokReviewResult:
    settings = get_settings()
    client = openai.AsyncOpenAI(api_key=settings.xai_api_key, base_url=settings.xai_base_url)
    user_payload = {
        "supplied_facts": facts,
        content_label: generated_content,
    }
    try:
        response = await client.chat.completions.create(
            model=settings.grok_model,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": json.dumps(user_payload, sort_keys=True)},
            ],
            response_format={
                "type": "json_schema",
                "json_schema": {"name": "grounding_review", "schema": _REVIEW_SCHEMA, "strict": True},
            },
            reasoning_effort=settings.xai_reasoning_effort,
        )
    except openai.OpenAIError as exc:
        raise GrokUnavailableError(str(exc)) from exc

    choice = response.choices[0] if response.choices else None
    content = choice.message.content if choice is not None else None
    if not content:
        raise GrokUnavailableError("Grok response contained no content")

    try:
        data = json.loads(content)
        return GrokReviewResult.model_validate(data)
    except (json.JSONDecodeError, ValidationError) as exc:
        raise GrokUnavailableError(f"Grok output failed schema validation: {exc}") from exc


async def review_draft(*, facts: dict, draft: dict) -> GrokReviewResult:
    """Review a Claude-generated SOAP draft for grounding. Raises `GrokUnavailableError`."""
    return await _review(facts=facts, generated_content=draft, content_label="generated_draft")


async def review_summary(*, facts: dict, summary: dict) -> GrokReviewResult:
    """Review a Claude-generated patient summary for grounding. Raises `GrokUnavailableError`."""
    return await _review(facts=facts, generated_content=summary, content_label="generated_summary")
